# Generated by Django 5.2.1 on 2025-05-18 22:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0002_alumno_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='curso',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
