# Generated by Django 5.2.1 on 2025-05-18 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0004_alter_alumno_nombre_alter_curso_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='nacimiento',
        ),
    ]
